name: LD_env
channels:
  - conda-forge
  - defaults

dependencies:
  # specify a Python version
  - python=3.10

  # core scientific packages
  - numpy
  - scipy
  - matplotlib
  - tifffile
  - scikit-learn
  
  # image processing
  - opencv
